version: "3"

services:
  authjs-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: authjs-keycloak
    volumes:
      - /home/ec2-user/certificates:/certificates
    networks:
      - web
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: >
      start
      --features=token-exchange
      --https-certificate-file=/certificates/cert.pem
      --https-certificate-key-file=/certificates/key.pem
      --hostname=${KEYCLOAK_HOSTNAME}
      --hostname-debug=true
    ports:
      - 8443:8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deluge.entrypoints=https"
      - "traefik.http.routers.deluge.rule=Host(`keycloak.authjs.dev`)"
      - "traefik.http.routers.deluge.tls.certresolver=tls"
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ec2-user/keycloak/traefik/traefik.toml:/traefik.toml:ro
      - /home/ec2-user/keycloak/traefik/config.toml:/config.toml:ro
      - /home/ec2-user/keycloak/traefik/acme.json:/acme.json
    networks:
      - web
    command:
      - "--configFile=/traefik.toml"

networks:
  web:
    external: true
